services:
  nginx:
    image: ${BASE_REGISTRY}:nginx-${IMG_TAG}
    container_name: nginx-proxy
    ports:
      - "${HOST_PORT}:80"
    networks:
      - web-network
    restart: unless-stopped
    depends_on:
      - go-app
      - nodejs-app
      - python-app
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==${NODE_TAG}"

  python-app:
    image: ${BASE_REGISTRY}:python-${IMG_TAG}
    container_name: python-app
    expose:
      - "8080"
    networks:
      - web-network
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==${NODE_TAG}"

  nodejs-app:
    image: ${BASE_REGISTRY}:nodejs-${IMG_TAG}
    container_name: nodejs-app
    expose:
      - "8080"
    networks:
      - web-network
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==${NODE_TAG}"

  go-app:
    image: ${BASE_REGISTRY}:go-${IMG_TAG}
    container_name: go-app
    expose:
      - "8080"
    networks:
      - web-network
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==${NODE_TAG}"

networks:
  web-network:
    driver: overlay
